version: "3"

services: 
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./lib:/var/lib/letsencrypt
    entrypoint: bash - c "letsencrypt certonly --standalone --non-interactive --agree-tos -m ${EMAIL} -d ${DOMAIN} &&\
                cp /etc/letsencrypt/live/${DOMAIN}/privkey.pem /etc/letsencrypt/live/${DOMAIN}/domain.key && \
                cat /etc/letsencrypt/live/${DOMAIN}/cert.pem /etc/letsencrypt/live/${DOMAIN}/chain.pem > domain.crt"
