version: "3"

services:
  letsencrypt:
    image: quay.io/letsencrypt/letsencrypt:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/etc/letsencrypt
      - ./lib:/var/lib/letsencrypt
    depends_on: registry
    entrypoint: letsencrypt certonly --standalone --non-interactive --agree-tos -m ${EMAIL} -d ${DOMAIN}

  registry:
    container_name: registry
    restart: always
    image: registry:latest
    ports:
      - 443:443
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: ./certs/live/${DOMAIN}/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: ./certs/live/${DOMAIN}/privkey.pem
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE: "s3"
      REGISTRY_STORAGE_S3_REGION: ${S3_REGION}
      REGISTRY_STORAGE_S3_BUCKET: ${S3_BUCKET}
      REGISTRY_STORAGE_S3_ACCESSKEY: ${S3_ACCESSKEY}
      REGISTRY_STORAGE_S3_SECRETKEY: ${S3_SECRETKEY}
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: "/data/auth/htpasswd"
    volumes:
      - ./certs:/certs
      - ./data:/data
