version: "3.4"

services:
  nginx:
    container_name: nginx
    image: docker_registry:latest 
    build:
      context: ./nginx
      args:
        - REGISTRY_USER=${USER}
        - REGISTRY_PASSWORD=${PASSWORD}
        - DOMAIN=${DOMAIN}
      dockerfile: ./nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    networks:
      - my-registry-network
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"

  registry:
    container_name: registry
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE: "s3"
      REGISTRY_STORAGE_S3_REGION: ${S3_REGION}
      REGISTRY_STORAGE_S3_BUCKET: ${S3_BUCKET}
      REGISTRY_STORAGE_S3_ACCESSKEY: ${S3_ACCESSKEY}
      REGISTRY_STORAGE_S3_SECRETKEY: ${S3_SECRETKEY}
    volumes:
      - ./data:/data
    networks:
      - my-registry-network
    logging:
      driver: "json-file"
      options:
        max-size: "1000k"
        max-file: "3"

networks:
  my-registry-network:
    driver: bridge
